using System.Collections.Generic;

namespace FlashEditor.Definitions.Interfaces {
    /// <summary>
    ///     Candidate names for index 3, every one of which re-hashes to the identifier both
    ///     caches hold for that exact row.
    /// </summary>
    /// <remarks>
    ///     <b>This table is a list of candidates, not a list of answers.</b> <see cref="InterfaceNames"/>
    ///     re-hashes every entry against the identifier the loaded cache actually holds before
    ///     showing it, so an entry that is wrong, or right for a different build, reads as
    ///     unnamed rather than as a false name. Nothing here is trusted on its own authority.
    ///     <para>
    ///     Regenerating it is described in <see cref="InterfaceNames"/>. Each entry cleared
    ///     three filters: it re-hashes to the stored identifier, it does so in <i>both</i> the
    ///     vanilla b639 capture and the repack wherever both declare the row, and the route that
    ///     produced it beat a length-preserving decoy null by a margin recorded there.
    ///     </para>
    /// </remarks>
    internal static class InterfaceNameTable {
        /// <summary>Candidate interface names, keyed by group id.</summary>
        internal static readonly Dictionary<int, string> Groups = new Dictionary<int, string>(434) {
            { 0, "100guide_eggs_overlay" },
            { 1, "100guide_flour_overlay" },
            { 2, "100guide_inv_flour" },
            { 3, "100guide_milk_overlay" },
            { 4, "tog_water_bowl" },
            { 5, "agilityarena_overlay" },
            { 6, "agilityarena_trade" },
            { 7, "ahoy_blackout" },
            { 8, "ahoy_islandmap" },
            { 9, "ahoy_runedraw" },
            { 10, "ahoy_windspeed" },
            { 11, "bank_deposit_box" },
            { 13, "bankpin_main" },
            { 14, "bankpin_settings" },
            { 16, "banner_anti_virus" },
            { 21, "banner_scamming" },
            { 22, "banner_security" },
            { 23, "banner_xmas" },
            { 24, "barrows_overlay" },
            { 25, "barrows_puzzle" },
            { 28, "blast_furnace_bar_stock" },
            { 29, "blast_furnace_plan_scroll" },
            { 30, "blast_furnace_temp_gauge" },
            { 31, "boardgames_challenge" },
            { 32, "boardgames_draughts" },
            { 34, "notes" },
            { 36, "boardgames_runelink" },
            { 40, "boardgames_runesquares" },
            { 43, "boardgames_runesquares_view" },
            { 44, "boardgames_runeversi" },
            { 48, "bob_locator_amulet" },
            { 51, "burgh_map" },
            { 52, "canoe" },
            { 53, "canoe_stations_map" },
            { 54, "castlewars_catapult" },
            { 55, "castlewars_score" },
            { 56, "castlewars_shopside" },
            { 57, "castlewars_status_overlay" },
            { 58, "castlewars_status_overlay_saradomin" },
            { 59, "castlewars_status_overlay_zamorak" },
            { 60, "castlewars_trade" },
            { 61, "cat_naming" },
            { 62, "cave_goblin_markers" },
            { 63, "champions_scroll" },
            { 64, "chat1" },
            { 65, "chat2" },
            { 66, "chat3" },
            { 67, "chat4" },
            { 68, "chat_np1" },
            { 69, "chat_np2" },
            { 70, "chat_np3" },
            { 71, "chat_np4" },
            { 90, "npcchat_np4_overlay" },
            { 91, "npcchat_np3_overlay" },
            { 92, "npcchat_np1_overlay" },
            { 93, "npcchat_np2_overlay" },
            { 94, "confirm_destroy" },
            { 95, "sailing_transport_world_map" },
            { 96, "darkness_dark" },
            { 97, "darkness_light" },
            { 98, "darkness_medium" },
            { 99, "death_dice" },
            { 100, "deep_blue" },
            { 103, "pattern_next" },
            { 105, "stockmarket" },
            { 107, "stockside" },
            { 109, "stockcollect" },
            { 112, "dwarf_rock_cannon" },
            { 113, "dwarf_rock_schematics" },
            { 114, "dwarf_rock_schematics_control" },
            { 117, "enakh_film" },
            { 118, "enakh_smoke_overlay" },
            { 120, "fade_to_black" },
            { 121, "fade_to_light_blue" },
            { 122, "fade_to_white" },
            { 123, "fairy_certificate" },
            { 125, "farming_tools" },
            { 126, "farming_tools_side" },
            { 127, "favour_keyring" },
            { 131, "doubleobjbox" },
            { 132, "garden_list" },
            { 133, "garden_quiz" },
            { 135, "aide_compass" },
            { 137, "chatdefault" },
            { 138, "glidermap" },
            { 139, "gnomeball" },
            { 142, "horror_metaldoor" },
            { 144, "hauntedmine_controls" },
            { 148, "objbox_overlay" },
            { 149, "inventory" },
            { 150, "keldagrim_map" },
            { 151, "keldagrim_story1" },
            { 152, "keldagrim_titles" },
            { 153, "aide_death" },
            { 155, "legends_mirror" },
            { 157, "quickchat_tutorial" },
            { 160, "rocko_kittens" },
            { 161, "smki_assignment" },
            { 163, "smki_learn" },
            { 164, "smki_buy" },
            { 165, "smki_smoke_overlay" },
            { 166, "rocko_cannonball" },
            { 167, "rocko_underwater" },
            { 168, "rocko_seagull" },
            { 170, "fade_from_black" },
            { 173, "chatlarge" },
            { 174, "wom_scroll" },
            { 175, "heat_overlay" },
            { 177, "fade_from_white" },
            { 179, "light_blue" },
            { 180, "lightning_flash" },
            { 182, "logout" },
            { 185, "macro_combilock" },
            { 186, "macro_evil_bob" },
            { 187, "music_v3" },
            { 188, "macro_mime_emotes" },
            { 191, "macro_quizshow" },
            { 192, "magic" },
            { 193, "magic_zaros" },
            { 196, "magictraining_grave" },
            { 197, "magictraining_shop" },
            { 198, "magictraining_tele" },
            { 209, "mazetimer" },
            { 210, "message1" },
            { 211, "message2" },
            { 212, "message3" },
            { 213, "message4" },
            { 214, "message5" },
            { 215, "message_np1" },
            { 216, "message_np2" },
            { 217, "message_np3" },
            { 218, "message_np4" },
            { 219, "message_np5" },
            { 220, "messagescroll" },
            { 221, "messagescroll2" },
            { 223, "peng_emote" },
            { 224, "misc_shipjourney" },
            { 225, "mm_message" },
            { 226, "mole_mud" },
            { 227, "mourning_deathalter_list" },
            { 228, "multi2" },
            { 229, "multi2_chat" },
            { 230, "multi3" },
            { 231, "multi3_chat" },
            { 232, "multi4" },
            { 233, "multi4_chat" },
            { 234, "multi5" },
            { 235, "multi5_chat" },
            { 236, "multivar2" },
            { 237, "multivar4" },
            { 238, "multivar5" },
            { 241, "npcchat1" },
            { 242, "npcchat2" },
            { 243, "npcchat3" },
            { 244, "npcchat4" },
            { 245, "npcchat_np1" },
            { 246, "npcchat_np2" },
            { 247, "npcchat_np3" },
            { 248, "npcchat_np4" },
            { 249, "surok_letter1" },
            { 250, "surok_letter2" },
            { 252, "olaf2_lock_gate" },
            { 253, "olaf2_skull_puzzle" },
            { 254, "olaf2_treasuremap" },
            { 259, "area_task" },
            { 260, "dream_armour" },
            { 261, "options" },
            { 263, "pinball_interface" },
            { 264, "paint_cannon" },
            { 265, "clanwars_overlay" },
            { 267, "pest_rewards" },
            { 271, "prayer" },
            { 272, "priestperil_gravemonument" },
            { 273, "prisonpete" },
            { 275, "questjournal_scroll" },
            { 282, "ratcatcher_flute" },
            { 283, "ratcatcher_flute_music" },
            { 284, "ratcatcher_overlay" },
            { 285, "rd_combolock" },
            { 286, "regicide_still" },
            { 290, "roguesden_dials" },
            { 293, "roguesden_puzzle" },
            { 295, "rum_deal_title" },
            { 296, "sandstorm" },
            { 298, "seer_combolock" },
            { 300, "smithing_new" },
            { 307, "banner_easter09" },
            { 310, "slayer_staff_spells" },
            { 315, "soulbane_angerbar" },
            { 317, "soulbane_darkness" },
            { 318, "soulbane_scare" },
            { 319, "staff_spells" },
            { 320, "stats" },
            { 321, "swamp_boatjourney" },
            { 322, "swamp_boatjourney_back" },
            { 324, "tanner" },
            { 325, "target" },
            { 326, "teleport_other" },
            { 327, "cws_warning_11" },
            { 328, "temple_screen" },
            { 329, "templetrek_map" },
            { 334, "tradeconfirm" },
            { 335, "trademain" },
            { 336, "tradeside" },
            { 345, "trail_cluelong" },
            { 346, "trail_map01" },
            { 347, "trail_map02" },
            { 348, "trail_map03" },
            { 349, "trail_map04" },
            { 350, "trail_map05" },
            { 351, "trail_map06" },
            { 352, "trail_map07" },
            { 353, "trail_map08" },
            { 354, "trail_map09" },
            { 355, "trail_map10" },
            { 356, "trail_map11" },
            { 357, "trail_map12" },
            { 358, "trail_map13" },
            { 359, "trail_map14" },
            { 360, "trail_map15" },
            { 361, "trail_map16" },
            { 362, "trail_map17" },
            { 363, "trail_puzzle" },
            { 364, "trail_reward" },
            { 365, "trail_sextant" },
            { 366, "trawler_overlay" },
            { 367, "trawler_reward" },
            { 368, "trawler_start" },
            { 371, "tutorial_progress" },
            { 372, "tutorial_text" },
            { 373, "tzhaar_fightpit" },
            { 374, "tzhaar_fightpit_orb" },
            { 378, "smki_learn2" },
            { 379, "werewolf_goal" },
            { 380, "welcome_final_tex" },
            { 381, "wilderness_overlay" },
            { 382, "wilderness_warning" },
            { 386, "wom_telescope" },
            { 387, "wornitems" },
            { 389, "objdialog" },
            { 393, "poh_hangman" },
            { 398, "poh_house_options" },
            { 400, "poh_magic_tablets" },
            { 401, "poh_ranging" },
            { 403, "poh_sawmill" },
            { 404, "poh_scrying_pool" },
            { 405, "banner_poh" },
            { 406, "pest_mace" },
            { 407, "pest_lander_overlay" },
            { 408, "pest_status_overlay" },
            { 409, "mcannon_interface" },
            { 410, "warguild_defence" },
            { 411, "warguild_defence_mini" },
            { 412, "warguild_dummy" },
            { 414, "brew_game_over" },
            { 415, "brew_overlay" },
            { 416, "brew_worktable" },
            { 417, "brew_tools" },
            { 421, "tutorial_text2" },
            { 423, "fairy2_certificate_broken" },
            { 424, "fairy2_message" },
            { 427, "scroll_godfather" },
            { 428, "ntk_overlay" },
            { 430, "magic_lunar" },
            { 432, "xbows_enchant_bolt" },
            { 433, "xbows_pouch" },
            { 438, "crafting_silver_casting" },
            { 445, "openurl" },
            { 446, "crafting_gold" },
            { 447, "banner_chatheads" },
            { 448, "brain_water_overlay" },
            { 451, "multivar3" },
            { 452, "myq3_statue_painting" },
            { 453, "myq3_blackout" },
            { 454, "myq3_boat_map" },
            { 461, "seaslug_boat_travel" },
            { 463, "kings_letter_v2" },
            { 464, "emotes" },
            { 469, "zep_balloon_map" },
            { 470, "zep_interface" },
            { 471, "zep_interface_side" },
            { 480, "anma_rgb" },
            { 484, "barbassault_horn" },
            { 485, "barbassault_over_att" },
            { 486, "barbassault_over_col" },
            { 487, "barbassault_over_def" },
            { 488, "barbassault_over_heal" },
            { 490, "barbassault_playerstat" },
            { 494, "barbassault_timer_overlay" },
            { 495, "barbassault_turret" },
            { 496, "barbassault_tutorial" },
            { 497, "barbassault_wavecomplete" },
            { 498, "contact_scroll_blood" },
            { 499, "skill_guide_v2" },
            { 507, "poh_hangman_german" },
            { 508, "tol_homonculus_overlay" },
            { 509, "tol_cage_puzzle" },
            { 510, "tol_pressure_machine" },
            { 511, "tol_pipe_machine" },
            { 512, "inventory_ranging" },
            { 514, "brain_cat_overlay" },
            { 515, "brain_gas_overlay" },
            { 519, "objbox" },
            { 521, "dream_cyrisus" },
            { 522, "dream_monster_stat" },
            { 523, "dream_player_stats" },
            { 524, "dream_title" },
            { 528, "vm_digsite" },
            { 532, "vm_kudos" },
            { 534, "vm_timeline" },
            { 538, "grim_tasklist" },
            { 539, "noexit" },
            { 543, "dragon_slayer_qip_clouds" },
            { 544, "dragon_slayer_qip_cr_journey" },
            { 545, "dragon_slayer_qip_elvarg" },
            { 546, "dragon_slayer_qip_elvarg_fly" },
            { 547, "dragon_slayer_qip_map" },
            { 548, "toplevel" },
            { 550, "friends2" },
            { 551, "ignore2" },
            { 557, "multi2_mes" },
            { 559, "pattern_cards" },
            { 560, "cws_warning_9" },
            { 562, "cws_warning_2" },
            { 563, "cws_warning_5" },
            { 564, "cws_warning_23" },
            { 565, "cws_warning_10" },
            { 566, "cws_warning_6" },
            { 567, "cws_warning_14" },
            { 568, "cws_warning_3" },
            { 569, "cws_warning_16" },
            { 570, "cws_warning_17" },
            { 571, "cws_warning_19" },
            { 572, "cws_warning_13" },
            { 573, "cws_warning_12" },
            { 574, "cws_warning_1" },
            { 576, "cws_warning_8" },
            { 577, "cws_warning_18" },
            { 578, "cws_warning_15" },
            { 579, "cws_warning_4" },
            { 580, "cws_warning_20" },
            { 581, "cws_warning_24" },
            { 583, "cws_doomsayer" },
            { 584, "kr_king_statue" },
            { 585, "kr_pyramid_escape" },
            { 588, "kr_picklock" },
            { 589, "clanjoin" },
            { 590, "clansetup" },
            { 596, "login" },
            { 600, "cws_warning_25" },
            { 601, "godwars_overlay" },
            { 620, "shop_template" },
            { 621, "shop_template_side" },
            { 622, "banner_group" },
            { 623, "banner_group_assist" },
            { 627, "cws_warning_26" },
            { 628, "duel2_side" },
            { 632, "duel2_scoreboard" },
            { 638, "duel2_challengeoverlay" },
            { 640, "duel2_select_type" },
            { 643, "exchange_history" },
            { 644, "exchange_sets_side" },
            { 645, "exchange_itemsets" },
            { 646, "exchange_sand_timer" },
            { 649, "clanwars_viewing_orb" },
            { 650, "cws_warning_30" },
            { 652, "gravestone_shop" },
            { 662, "lore_stats_side" },
            { 663, "lore_cats_side" },
            { 665, "lore_bank_side" },
            { 667, "equip_screen2" },
            { 670, "inventory_wear2" },
            { 671, "lore_bank" },
            { 676, "cws_warning_27" },
            { 677, "cws_warning_28" },
            { 678, "cws_warning_29" },
            { 679, "banner_summoning" },
            { 686, "rabbit_shop" },
            { 689, "rabbit_overlay" },
            { 715, "banner_easter08" },
            { 722, "summoning_side" },
            { 742, "graphics_options" },
            { 743, "sound_options" },
            { 744, "loginscreen" },
            { 745, "statusicons" },
            { 746, "toplevel_fullscreen" },
            { 747, "topstat_lore" },
            { 748, "topstat_hitpoints" },
            { 749, "topstat_prayer" },
            { 750, "topstat_run" },
            { 751, "filterbuttons" },
            { 752, "chattop" },
            { 754, "pmchat" },
            { 755, "worldmap" },
            { 756, "boardgames_options" },
            { 757, "npcchatlarge" },
            { 758, "canoe_travel" },
            { 762, "bank_v2_main" },
            { 763, "bank_v2_side" },
            { 767, "bank_v2_help" },
            { 769, "boardgames_view" },
            { 778, "rcguild_side" },
            { 779, "rcguild_rewards" },
            { 780, "rcguild_map" },
            { 781, "rcguild_overlay" },
            { 783, "crcs_tightrope" },
            { 784, "crcs_side" },
            { 785, "crcs_rewards" },
            { 786, "crcs_equipment" },
            { 788, "crcs_scoreboard" },
            { 790, "clanwars_end" },
            { 791, "clanwars_setup" },
            { 792, "clanwars_setup_side" },
            { 800, "banner_halloween" },
            { 801, "quickchat_locked" },
            { 802, "sc_tutorial_overlay" },
            { 803, "sc_scores_border" },
            { 805, "sc_item_transfer" },
            { 806, "sc_remaining_clay" },
            { 807, "sc_item_transfer_side" },
            { 810, "sc_scores" },
            { 811, "sc_reward_shop" },
            { 813, "sc_processing" },
            { 814, "luc2_chapter2" },
            { 816, "luc2_telescope_view" },
            { 822, "luc2_chapter3" },
            { 826, "luc2_chapter1" },
            { 827, "luc2_lucien_projectiles" },
            { 882, "loginscreen_graphics_options" },
            { 883, "graphics_confirm" },
            { 892, "cws_warning_33" },
            { 906, "lobbyscreen" },
            { 952, "bind" },
            { 983, "castlewars_orb" }
        };

        /// <summary>
        ///     Candidate component names that the <c>com_&lt;fileId&gt;</c> rule cannot produce,
        ///     keyed by group id and then by file id within it.
        /// </summary>
        /// <remarks>
        ///     Two levels rather than a flat tuple key because a component id is only meaningful
        ///     inside its group: file 3 of one interface has nothing to do with file 3 of another,
        ///     and a flat key invites exactly that confusion at the call site.
        /// </remarks>
        internal static readonly Dictionary<int, Dictionary<int, string>> Components =
            new Dictionary<int, Dictionary<int, string>> {
                { 7, new Dictionary<int, string> { { 1, "ahoy_blackout_message" } } },
                { 31, new Dictionary<int, string> { { 4, "boardgames_challenge_select" } } },
                { 40, new Dictionary<int, string> { { 1, "boardgames_runesquares_to" }, { 2, "boardgames_runesquares_v2" }, { 3, "boardgames_runesquares_v3" }, { 10, "boardgames_runesquares_to0" }, { 11, "boardgames_runesquares_to1" }, { 12, "boardgames_runesquares_to2" }, { 13, "boardgames_runesquares_to3" }, { 14, "boardgames_runesquares_to4" }, { 15, "boardgames_runesquares_to5" }, { 16, "boardgames_runesquares_to6" }, { 17, "boardgames_runesquares_to7" }, { 18, "boardgames_runesquares_to8" }, { 19, "boardgames_runesquares_to9" }, { 20, "boardgames_runesquares_v20" }, { 21, "boardgames_runesquares_v21" }, { 22, "boardgames_runesquares_v22" }, { 23, "boardgames_runesquares_v23" }, { 24, "boardgames_runesquares_v24" }, { 25, "boardgames_runesquares_v25" }, { 26, "boardgames_runesquares_v26" }, { 27, "boardgames_runesquares_v27" }, { 28, "boardgames_runesquares_v28" }, { 29, "boardgames_runesquares_v29" } } },
                { 63, new Dictionary<int, string> { { 3, "champions_scroll_text" } } },
                { 95, new Dictionary<int, string> { { 0, "sailing_transport_world_map" } } },
                { 131, new Dictionary<int, string> { { 1, "doubleobjbox_text" } } },
                { 132, new Dictionary<int, string> { { 3, "garden_list_1" }, { 4, "garden_list_2" }, { 5, "garden_list_3" }, { 6, "garden_list_4" }, { 7, "garden_list_5" }, { 8, "garden_list_6" }, { 9, "garden_list_7" }, { 10, "garden_list_8" }, { 11, "garden_list_9" }, { 12, "garden_list_10" }, { 13, "garden_list_11" } } },
                { 133, new Dictionary<int, string> { { 6, "garden_quiz_title" } } },
                { 252, new Dictionary<int, string> { { 0, "olaf2_lock_gate" } } },
                { 254, new Dictionary<int, string> { { 1, "olaf2_treasuremap" } } },
                { 259, new Dictionary<int, string> { { 9, "area_task" }, { 11, "area_task_0" }, { 16, "area_task_1" }, { 21, "area_task_2" }, { 26, "area_task_3" }, { 31, "area_task_4" }, { 36, "area_task_5" } } },
                { 364, new Dictionary<int, string> { { 1, "trail_reward_scroll" }, { 4, "trail_reward_box" } } },
                { 371, new Dictionary<int, string> { { 0, "tutorial_progress_overlay" } } },
                { 373, new Dictionary<int, string> { { 2, "tzhaar_fightpit_remaining" } } },
                { 389, new Dictionary<int, string> { { 6, "objdialog_title" } } },
                { 393, new Dictionary<int, string> { { 0, "poh_hangman_letter1" }, { 1, "poh_hangman_letter2" } } },
                { 484, new Dictionary<int, string> { { 8, "barbassault_horn_att" }, { 10, "barbassault_horn_col" }, { 11, "barbassault_horn_heal" } } },
                { 507, new Dictionary<int, string> { { 0, "poh_hangman_german_letter1" }, { 1, "poh_hangman_german_letter2" } } },
                { 519, new Dictionary<int, string> { { 1, "objbox_text" } } },
                { 528, new Dictionary<int, string> { { 2, "vm_digsite_text" } } },
                { 532, new Dictionary<int, string> { { 1, "vm_kudos" } } },
                { 534, new Dictionary<int, string> { { 2, "vm_timeline_text" } } },
                { 745, new Dictionary<int, string> { { 0, "statusicons" } } },
                { 747, new Dictionary<int, string> { { 0, "topstat_lore" } } },
                { 749, new Dictionary<int, string> { { 0, "topstat_prayer" } } },
                { 754, new Dictionary<int, string> { { 0, "pmchat" } } },
                { 755, new Dictionary<int, string> { { 28, "worldmap" }, { 29, "worldmap_overlay" } } },
                { 788, new Dictionary<int, string> { { 15, "crcs_scoreboard_scroll" } } },
                { 816, new Dictionary<int, string> { { 0, "luc2_telescope_view" } } },
                { 952, new Dictionary<int, string> { { 0, "bind" }, { 1, "bind_back" } } }
            };
    }
}
